# Use a Node base image
FROM node:24-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose the port used by Parcel
EXPOSE 1234

# Command to run the Parcel server
CMD ["npm", "start"]
