version: "3"
services:
  database:
    image: postgres:16
    volumes:
      - ./backend/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
  cache:
    image: redis:6
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./backend/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    env_file:
      - .env