version: "3"
services:
  database:
    image: postgres:16
    volumes:
      - ./backend/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
  directus:
    image: directus/directus:11.8
    ports:
      - 8055:8055
    volumes:
      - ./backend/uploads:/directus/uploads
      - ./backend/extensions:/directus/extensions
      - ./backend/snapshots:/directus/snapshots
    depends_on:
      - database
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "1234:1234"
    env_file:
      - .env
