# Use Directus official image as the base
FROM directus/directus:10.9

# Copy your extensions into the image
# Ensure your extensions are compatible with Directus version you're extending
COPY ./backend/extensions /directus/extensions
