app = "bnn-directus-prod"
primary_region = "fra"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2

[http_service.concurrency]
  type = "requests"
  hard_limit = 100
  soft_limit = 80

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  NODE_ENV = "production"
  PORT = "8055"

[[checks]]
  name = "directus-health"
  grace_period = "30s"
  interval = "30s"
  method = "get"
  path = "/server/ping"
  port = 8055
  timeout = "10s"
  type = "http"