name: CI to Docker Hub and Deploy to Google Cloud Run

on:
  push:
    branches:
      - 'feature/deploy-directus'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            j0hngnn0n/bnn:frontend-${{ github.sha }}
            j0hngnn0n/bnn:latest

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Deploy Google Cloud Run bnn-frontend'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'bnn-frontend'
          image: 'j0hngnn0n/bnn:frontend-${{ github.sha }}'
          region: 'europe-west6'
      
      - name: 'Deploy Google Cloud Run bnn-directus'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          metadata: 'deploy/bnn-directus.yaml'
          region: 'europe-west6'
          service: 'bnn-directus'
          

