name: CI to Docker Hub

on:
  push:
    branches:
      - 'main' # Trigger on pushes to main branch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            j0hngnn0n/bnn:frontend-${{ github.sha }}
            j0hngnn0n/bnn:latest

      # This step might need adjustment as "docker_build" needs to match the id of the build step if you want to use outputs
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
