name: CI to Docker Hub and Deploy to Google Cloud Run

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            j0hngnn0n/bnn-frontend:${{ github.sha }}
            j0hngnn0n/bnn-frontend:latest
      
      - name: Build and push Directus custom Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            j0hngnn0n/bnn-directus:${{ github.sha }}
            j0hngnn0n/bnn-directus:latest

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: 'Upload snapshot to gcs'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './backend/snapshots/snapshot-latest.yaml'
          destination: 'bnn-directus-snapshots/snapshot-latest.yaml'

      - name: Deploy directus to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: 'europe-west6'
          service: 'bnn-directus'
          image: j0hngnn0n/bnn-directus:${{ github.sha }}
          flags: '--add-cloudsql-instances=bnn-app-413420:europe-west6:bnn-database'
          env_vars: |
            KEY=${{ secrets.DIRECTUS_KEY }}
            SECRET=${{ secrets.DIRECTUS_SECRET }}
            APPLY_SNAPSHOT=true
            ADMIN_EMAIL=gannonline90@gmail.com
            ADMIN_PASSWORD=${{ secrets.DIRECTUS_ADMIN_PASSWORD }}
            CORS_ENABLED=true
            CORS_ORIGIN=https://bnn-frontend-g5zcbtf63q-oa.a.run.app
            CORS_METHODS=GET,POST,PATCH,DELETE
            CORS_ALLOWED_HEADERS=Content-Type,Authorization
            CORS_EXPOSED_HEADERS=Content-Range
            EMAIL_TRANSPORT=smtp
            EMAIL_SMTP_HOST=mail.infomaniak.com
            EMAIL_SMTP_PORT=465
            EMAIL_SMTP_SECURE=true
            EMAIL_SMTP_AUTH=true
            EMAIL_SMTP_USER=info@beimnamennennen.ch
            EMAIL_SMTP_PASSWORD=${{ secrets.DIRECTUS_SMTP_PASSWORD }}
            EMAIL_FROM=info@beimnamennennen.ch
            DB_CLIENT=pg
            DB_CONNECTION_STRING=${{ secrets.DIRECTUS_DB_CONNECTION_STRING }}
            STORAGE_LOCATIONS=gcs
            STORAGE_GCS_DRIVER=gcs
            STORAGE_GCS_ROOT=./uploads
            STORAGE_GOOGLE_CREDENTIALS__PRIVATE_KEY=${{ secrets.GCP_SA_PRIVATE_KEY }}
            STORAGE_GOOGLE_CREDENTIALS__CLIENT_EMAIL=${{ secrets.GCP_SA_CLIENT_EMAIL }}
            STORAGE_GCS_BUCKET=directus-uploads
            PRESSURE_LIMITER_ENABLED=false

      - name: Get Directus Service URL
        id: get_backend_url
        run: |
          BACKEND_SERVICE_URL=$(gcloud run services describe bnn-directus --platform managed --region europe-west6 --format 'value(status.url)')
          echo "BACKEND_SERVICE_URL=$BACKEND_SERVICE_URL" 
          echo "::set-output name=backend_service_url::$BACKEND_SERVICE_URL"

      - name: 'Deploy frontend to Google Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'bnn-frontend'
          image: 'j0hngnn0n/bnn-frontend:${{ github.sha }}'
          region: 'europe-west6'
          env_vars: |
            API_URL=${{ steps.get_backend_url.outputs.backend_service_url }}
