name: Deploy to Production

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-staging:
    uses: ./.github/workflows/common.yml
    with:
      environment: production
      frontend_service_name: 'bnn-frontend'
      directus_service_name: 'bnn-directus'
      frontend_url: 'https://bnn-frontend-g5zcbtf63q-oa.a.run.app'
      gcs_upload_directory: './uploads'
    secrets: inherit
