name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      frontend_app: bnn-frontend-prod
      backend_app: bnn-directus-prod
      db_app: bnn-db-prod
      frontend_url: https://bnn-frontend-prod.fly.dev
      backend_url: https://bnn-directus-prod.fly.dev
    secrets: inherit