name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      apply_snapshot:
        description: 'Apply Directus schema snapshot?'
        required: true
        type: boolean
        default: false

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      frontend_app: bnn-frontend-staging
      backend_app: bnn-directus-staging
      db_app: bnn-db-staging
      frontend_urls: https://staging.beimnamennennen.ch,https://staging.lesnommerparleurnom.ch,https://bnn-frontend-staging.fly.dev
      backend_urls: https://api.staging.beimnamennennen.ch,https://api.staging.lesnommerparleurnom.ch,https://bnn-directus-staging.fly.dev
      apply_snapshot: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply_snapshot || false }}
    secrets: inherit
