name: Deploy to Production

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      apply_snapshot:
        description: 'Apply Directus schema snapshot?'
        required: true
        type: boolean
        default: false

jobs:
  build-and-push-production:
    uses: ./.github/workflows/common.yaml
    with:
      environment: production
      frontend_service_name: 'bnn-frontend'
      directus_service_name: 'bnn-directus'
      frontend_url: https://www.beimnamennennen.ch
      backend_url: 'https://api.beimnamennennen.ch'
      gcs_upload_directory: './uploads'
      apply_snapshot: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply_snapshot || false }}
    secrets: inherit
