name: Deploy to Staging

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:
    inputs:
      apply_snapshot:
        description: 'Apply Directus schema snapshot?'
        required: true
        type: boolean
        default: false

jobs:
  build-and-push-staging:
    uses: ./.github/workflows/common.yaml
    with:
      environment: staging
      frontend_service_name: 'bnn-frontend-staging'
      directus_service_name: 'bnn-directus-staging'
      frontend_url: 'https://staging.beimnamennennen.ch'
      backend_url: 'https://api.staging.beimnamennennen.ch'
      gcs_upload_directory: './uploads-staging'
      apply_snapshot: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply_snapshot || false }}
    secrets: inherit

    
