name: Deploy to Staging

on:
  push:
    branches:
      - feature/fly-deployment

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      frontend_app: bnn-frontend-staging
      backend_app: bnn-directus-staging
      frontend_url: https://bnn-frontend-staging.fly.dev
      backend_url: https://bnn-directus-staging.fly.dev
    secrets: inherit