name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      apply_snapshot:
        description: "Apply the Directus schema snapshot?"
        required: true
        default: false
        type: boolean

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      frontend_app: bnn-frontend-prod
      backend_app: bnn-directus-prod
      db_app: bnn-db-prod
      frontend_url: https://bnn-frontend-prod.fly.dev
      backend_url: https://bnn-directus-prod.fly.dev
      apply_snapshot: ${{ inputs.apply_snapshot }}
    secrets: inherit