name: Deploy to Production

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-production:
    uses: ./.github/workflows/common.yaml
    with:
      environment: production
      frontend_service_name: 'bnn-frontend'
      directus_service_name: 'bnn-directus'
      frontend_url: 'https://beimnamennennen.ch'
      backend_url: 'https://api.beimnamennennen.ch'
      gcs_upload_directory: './uploads'
    secrets: inherit
