name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      apply_snapshot:
        description: 'Apply Directus schema snapshot?'
        required: true
        type: boolean
        default: false

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      frontend_app: bnn-frontend-prod
      backend_app: bnn-directus-prod
      db_app: bnn-db-prod
      frontend_urls: https://beimnamennennen.ch,https://www.beimnamennennen.ch,https://lesnommerparleurnom.ch,https://www.lesnommerparleurnom.ch,https://bnn-frontend-prod.fly.dev
      backend_urls: https://api.beimnamennennen.ch,https://api.beimnamennennen.ch,https://api.lesnommerparleurnom.ch,https://api.lesnommerparleurnom.ch,https://bnn-directus-prod.fly.dev
      apply_snapshot: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply_snapshot || false }}
    secrets: inherit

