name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      apply_snapshot:
        description: 'Apply Directus schema snapshot?'
        required: true
        type: boolean
        default: false

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      frontend_app: bnn-frontend-prod
      backend_app: bnn-directus-prod
      db_app: bnn-db-prod
      frontend_url: https://www.beimnamennennen.ch
      backend_url: 'https://api.beimnamennennen.ch'
      apply_snapshot: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply_snapshot || false }}
    secrets: inherit

