name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
      frontend_app: bnn-frontend-prod
      backend_app: bnn-directus-prod
      frontend_url: https://www.beimnamennennen.ch
      backend_url: https://api.beimnamennennen.ch
    secrets: inherit